title: <p align="center">Biswa P Samanta </p>
logo: /assets/img/biswa.jpg
description: 
  <p align="center">
  
  <br>
    I work as a Enterprise Data warehouse Specialist.
  </p>
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
